name: Build & Push Docker Image to ACR.

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Azure using your Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR using the same SP (AcrPush permission)
      - name: Login to ACR
        run: |
          az acr login --name viziappsdemoregistry

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t viziappsdemoregistry.azurecr.io/testapp:latest1 .

      # Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push viziappsdemoregistry.azurecr.io/testapp:latest1

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: dev
          containerAppName: test-app0213
          imageToDeploy: viziappsdemoregistry.azurecr.io/testapp:latest1
          acrName: viziappsdemoregistry
